/*
 * SEMP (Solace Element Management Protocol)
 *
 * SEMP (starting in `v2`) is a RESTful API for configuring, monitoring, and administering a Solace PubSub+ broker. This specification defines the following API:   API|Base Path|Purpose :---|:---|:--- Configuration|/SEMP/v2/config|Reading and writing configuration    The following APIs are also available:   API|Base Path|Purpose :---|:---|:--- Action|/SEMP/v2/action|Performing actions Monitoring|/SEMP/v2/monitor|Querying operational state    For tutorials, architectural and protocol design documentation, and other information about the SEMP API, consult the [SEMP documentation](https://docs.solace.com/Admin/SEMP/Using-SEMP.htm) on the Solace website. The SEMP API specifications are also [available for download](https://solace.com/downloads/).  If you need additional support, please contact us at [support@solace.com](mailto:support@solace.com).
 *
 * API version: 2.48
 * Contact: support@solace.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MsgVpnAclProfilePublishTopicException struct {
	// The name of the ACL Profile.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\".
	AclProfileName string `json:"aclProfileName,omitempty"`
	// The name of the Message VPN.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\".
	MsgVpnName string `json:"msgVpnName,omitempty"`
	// The topic for the exception to the default action taken. May include wildcard characters.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\".
	PublishTopicException string `json:"publishTopicException,omitempty"`
	// The syntax of the topic for the exception to the default action taken.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\". The allowed values and their meaning are:  <pre> \"smf\" - Topic uses SMF syntax. \"mqtt\" - Topic uses MQTT syntax. </pre> 
	PublishTopicExceptionSyntax string `json:"publishTopicExceptionSyntax,omitempty"`
}
