/*
 * SEMP (Solace Element Management Protocol)
 *
 * SEMP (starting in `v2`) is a RESTful API for configuring, monitoring, and administering a Solace PubSub+ broker. This specification defines the following API:   API|Base Path|Purpose :---|:---|:--- Configuration|/SEMP/v2/config|Reading and writing configuration    The following APIs are also available:   API|Base Path|Purpose :---|:---|:--- Action|/SEMP/v2/action|Performing actions Monitoring|/SEMP/v2/monitor|Querying operational state    For tutorials, architectural and protocol design documentation, and other information about the SEMP API, consult the [SEMP documentation](https://docs.solace.com/Admin/SEMP/Using-SEMP.htm) on the Solace website. The SEMP API specifications are also [available for download](https://solace.com/downloads/).  If you need additional support, please contact us at [support@solace.com](mailto:support@solace.com).
 *
 * API version: 2.48
 * Contact: support@solace.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MsgVpnRestDeliveryPointQueueBinding struct {
	// Enable or disable whether the authority for the request-target is replaced with that configured for the REST Consumer remote. When enabled, the broker sends HTTP requests in absolute-form, with the request-target's authority taken from the REST Consumer's remote host and port configuration. When disabled, the broker sends HTTP requests whose request-target matches that of the original request message, including whether to use absolute-form or origin-form. This configuration is applicable only when the Message VPN is in REST gateway mode.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\". The minimum access scope/level required to change this attribute is \"vpn/read-write\". Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `false`. Available since 2.6.
	GatewayReplaceTargetAuthorityEnabled **bool `json:"gatewayReplaceTargetAuthorityEnabled,omitempty"`
	// The name of the Message VPN.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\".
	MsgVpnName string `json:"msgVpnName,omitempty"`
	// The request-target string to use when sending requests. It identifies the target resource on the far-end REST Consumer upon which to apply the request. There are generally two common forms for the request-target. The origin-form is most often used in practice and contains the path and query components of the target URI. If the path component is empty then the client must generally send a \"/\" as the path. When making a request to a proxy, most often the absolute-form is required. This configuration is only applicable when the Message VPN is in REST messaging mode.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\". The minimum access scope/level required to change this attribute is \"vpn/read-write\". Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `\"\"`.
	PostRequestTarget string `json:"postRequestTarget,omitempty"`
	// The name of a queue in the Message VPN.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\".
	QueueBindingName string `json:"queueBindingName,omitempty"`
	// The type of evaluation to perform on the request target.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\". The minimum access scope/level required to change this attribute is \"vpn/read-write\". Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `\"none\"`. The allowed values and their meaning are:  <pre> \"none\" - Do not evaluate substitution expressions on the request target. \"substitution-expressions\" - Evaluate substitution expressions on the request target. </pre>  Available since 2.23.
	RequestTargetEvaluation string `json:"requestTargetEvaluation,omitempty"`
	// The name of the REST Delivery Point.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\".
	RestDeliveryPointName string `json:"restDeliveryPointName,omitempty"`
}
