/*
 * SEMP (Solace Element Management Protocol)
 *
 * SEMP (starting in `v2`) is a RESTful API for configuring, monitoring, and administering a Solace PubSub+ broker. This specification defines the following API:   API|Base Path|Purpose :---|:---|:--- Configuration|/SEMP/v2/config|Reading and writing configuration    The following APIs are also available:   API|Base Path|Purpose :---|:---|:--- Action|/SEMP/v2/action|Performing actions Monitoring|/SEMP/v2/monitor|Querying operational state    For tutorials, architectural and protocol design documentation, and other information about the SEMP API, consult the [SEMP documentation](https://docs.solace.com/Admin/SEMP/Using-SEMP.htm) on the Solace website. The SEMP API specifications are also [available for download](https://solace.com/downloads/).  If you need additional support, please contact us at [support@solace.com](mailto:support@solace.com).
 *
 * API version: 2.48
 * Contact: support@solace.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MsgVpnKafkaReceiverTopicBinding struct {
	// Enable or disable this topic binding of the Kafka Receiver.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\". The minimum access scope/level required to change this attribute is \"vpn/read-write\". Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `false`.
	Enabled **bool `json:"enabled,omitempty"`
	// The initial offset to consume from the Kafka Topic if no member of the group has consumed and committed any offset already, or if the last committed offset has been deleted. Offsets are unique per partition.  This corresponds to the Kafka consumer API `auto.offset.reset` configuration setting.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\". The minimum access scope/level required to change this attribute is \"vpn/read-write\". Modifying this attribute while the object (or the relevant part of the object) is administratively enabled may be service impacting as enabled will be temporarily set to false to apply the change. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `\"end\"`. The allowed values and their meaning are:  <pre> \"beginning\" - Start with the earliest offset available. \"end\" - Start with new offsets only. </pre> 
	InitialOffset string `json:"initialOffset,omitempty"`
	// The name of the Kafka Receiver.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\".
	KafkaReceiverName string `json:"kafkaReceiverName,omitempty"`
	// The Substitution Expression used to generate the key for each message received from Kafka. This expression can include fields extracted from the metadata of each individual Kafka message as it is received from the Kafka Topic.  If empty, no key is included for each message as it is published into Solace.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\". The minimum access scope/level required to change this attribute is \"vpn/read-write\". Modifying this attribute while the object (or the relevant part of the object) is administratively enabled may be service impacting as enabled will be temporarily set to false to apply the change. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `\"\"`.
	LocalKey string `json:"localKey,omitempty"`
	// The Substitution Expression used to generate the Solace Topic for each message received from Kafka. This expression can include data extracted from the metadata of each individual Kafka message as it is received from the Kafka Topic.  If empty, the Topic Binding will not be operational.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\". The minimum access scope/level required to change this attribute is \"vpn/read-write\". Modifying this attribute while the object (or the relevant part of the object) is administratively enabled may be service impacting as enabled will be temporarily set to false to apply the change. Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `\"\"`.
	LocalTopic string `json:"localTopic,omitempty"`
	// The name of the Message VPN.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\".
	MsgVpnName string `json:"msgVpnName,omitempty"`
	// The name of the Topic or a POSIX.2 regular expression starting with '^'.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\".
	TopicName string `json:"topicName,omitempty"`
}
