/*
 * SEMP (Solace Element Management Protocol)
 *
 * SEMP (starting in `v2`) is a RESTful API for configuring, monitoring, and administering a Solace PubSub+ broker. This specification defines the following API:   API|Base Path|Purpose :---|:---|:--- Configuration|/SEMP/v2/config|Reading and writing configuration    The following APIs are also available:   API|Base Path|Purpose :---|:---|:--- Action|/SEMP/v2/action|Performing actions Monitoring|/SEMP/v2/monitor|Querying operational state    For tutorials, architectural and protocol design documentation, and other information about the SEMP API, consult the [SEMP documentation](https://docs.solace.com/Admin/SEMP/Using-SEMP.htm) on the Solace website. The SEMP API specifications are also [available for download](https://solace.com/downloads/).  If you need additional support, please contact us at [support@solace.com](mailto:support@solace.com).
 *
 * API version: 2.48
 * Contact: support@solace.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MsgVpnAclProfile struct {
	// The name of the ACL Profile.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\".
	AclProfileName string `json:"aclProfileName,omitempty"`
	// The default action to take when a client using the ACL Profile connects to the Message VPN.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\". The minimum access scope/level required to change this attribute is \"vpn/read-write\". Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `\"disallow\"`. The allowed values and their meaning are:  <pre> \"allow\" - Allow client connection unless an exception is found for it. \"disallow\" - Disallow client connection unless an exception is found for it. </pre> 
	ClientConnectDefaultAction string `json:"clientConnectDefaultAction,omitempty"`
	// The name of the Message VPN.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\".
	MsgVpnName string `json:"msgVpnName,omitempty"`
	// The default action to take when a client using the ACL Profile publishes to a topic in the Message VPN.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\". The minimum access scope/level required to change this attribute is \"vpn/read-write\". Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `\"disallow\"`. The allowed values and their meaning are:  <pre> \"allow\" - Allow topic unless an exception is found for it. \"disallow\" - Disallow topic unless an exception is found for it. </pre> 
	PublishTopicDefaultAction string `json:"publishTopicDefaultAction,omitempty"`
	// The default action to take when a client using the ACL Profile subscribes to a share-name subscription in the Message VPN.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\". The minimum access scope/level required to change this attribute is \"vpn/read-write\". Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `\"allow\"`. The allowed values and their meaning are:  <pre> \"allow\" - Allow topic unless an exception is found for it. \"disallow\" - Disallow topic unless an exception is found for it. </pre>  Available since 2.14.
	SubscribeShareNameDefaultAction string `json:"subscribeShareNameDefaultAction,omitempty"`
	// The default action to take when a client using the ACL Profile subscribes to a topic in the Message VPN.  The minimum access scope/level required to retrieve this attribute is \"vpn/read-only\". The minimum access scope/level required to change this attribute is \"vpn/read-write\". Changes to this attribute are synchronized to HA mates and replication sites via config-sync. The default value is `\"disallow\"`. The allowed values and their meaning are:  <pre> \"allow\" - Allow topic unless an exception is found for it. \"disallow\" - Disallow topic unless an exception is found for it. </pre> 
	SubscribeTopicDefaultAction string `json:"subscribeTopicDefaultAction,omitempty"`
}
